version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: propellant
    ports:
      - "35432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    restart: unless-stopped
